logging:
  file: logs/mod-external-reference-resolver.log
  level:
    org:
      folio.rest: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO

server:
  port: 9003
  tomcat:
    connection-timeout: -1
    accept-count: 1000
    max-connections: 100000
    max-threads: 400

spring:
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    hikari:
      connectionTimeout: 172800000
      idleTimeout: 3600000
      maximumPoolSize: 100
    platform: h2
    url: jdbc:h2:./target/mod-external-reference-resolver;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    # platform: postgres
    # driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/mod-external-reference-resolver
    
    username: folio
    password: folio
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: target
  h2:
    console: 
      enabled: true
      path: /h2console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        dialect: org.folio.rest.dialect.CustomH2Dialect
        # dialect: org.folio.rest.dialect.CustomPostgreSQLDialect
        jdbc:
          batch_size: 100
          lob.non_contextual_creation: true

    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: true
    show-sql: true
  profiles:
    active: default
  thymeleaf:
    mode: TEXT
    suffix: .sql

tenant:
  header-name: X-Okapi-Tenant
  force-tenant: false
  default-tenant: diku
  initialize-default-tenant: true
  domain-packages:
  schema-scripts:
