logging:
  file: logs/mod-external-reference-resolver.log
  level:
    org:
      folio.rest: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO
  path:

server:
  port: 9000

spring:
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    # platform: h2
    # url: jdbc:h2:./target/mod-external-reference-resolver;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.h2.Driver
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mod-external-reference-resolver
    
    username: folio
    password: folio
  h2:
    console: 
      enabled: false
      path: /h2console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: true
    show-sql: true
  profiles:
    active: default
  thymeleaf:
    mode: TEXT
    suffix: .sql

tenant:
  header-name: X-Okapi-Tenant
  force-tenant: false
  default-tenant: diku
  initialize-default-tenant: false
  domain-packages:
  schema-scripts:
